// =============================================================================
// DATOS DE EJEMPLO DEL RANKING - Matemáticas en Verso
// =============================================================================

import type { JugadorRanking } from "@/tipos/ranking"

export const jugadoresRankingEjemplo: JugadorRanking[] = [
  {
    id: "user-1",
    nombreUsuario: "MagoMatematico",
    experienciaTotal: 2500,
    nivel: 12,
    rachaActual: 30,
    ejerciciosCompletados: 150,
    posicion: 1,
  },
  {
    id: "user-2",
    nombreUsuario: "DamaCuadratica",
    experienciaTotal: 2100,
    nivel: 10,
    rachaActual: 25,
    ejerciciosCompletados: 130,
    posicion: 2,
  },
  {
    id: "user-3",
    nombreUsuario: "EstudianteGenial",
    experienciaTotal: 1325,
    nivel: 7,
    rachaActual: 15,
    ejerciciosCompletados: 85,
    posicion: 3,
    esUsuarioActual: true,
  },
  {
    id: "user-4",
    nombreUsuario: "NinjaNumerico",
    experienciaTotal: 1200,
    nivel: 6,
    rachaActual: 12,
    ejerciciosCompletados: 75,
    posicion: 4,
  },
  {
    id: "user-5",
    nombreUsuario: "GeometraEstelar",
    experienciaTotal: 1100,
    nivel: 6,
    rachaActual: 10,
    ejerciciosCompletados: 70,
    posicion: 5,
  },
  {
    id: "user-6",
    nombreUsuario: "AlgebraPro",
    experienciaTotal: 950,
    nivel: 5,
    rachaActual: 8,
    ejerciciosCompletados: 60,
    posicion: 6,
  },
  {
    id: "user-7",
    nombreUsuario: "CalculoMaster",
    experienciaTotal: 850,
    nivel: 5,
    rachaActual: 5,
    ejerciciosCompletados: 55,
    posicion: 7,
  },
  {
    id: "user-8",
    nombreUsuario: "ProbabilidadX",
    experienciaTotal: 720,
    nivel: 4,
    rachaActual: 7,
    ejerciciosCompletados: 45,
    posicion: 8,
  },
  {
    id: "user-9",
    nombreUsuario: "VectoriaFeliz",
    experienciaTotal: 650,
    nivel: 4,
    rachaActual: 3,
    ejerciciosCompletados: 40,
    posicion: 9,
  },
  {
    id: "user-10",
    nombreUsuario: "IntegralKid",
    experienciaTotal: 580,
    nivel: 3,
    rachaActual: 2,
    ejerciciosCompletados: 35,
    posicion: 10,
  },
]

export const rankingSemanal: JugadorRanking[] = [
  {
    id: "user-3",
    nombreUsuario: "EstudianteGenial",
    experienciaTotal: 425,
    nivel: 7,
    rachaActual: 15,
    ejerciciosCompletados: 25,
    posicion: 1,
    esUsuarioActual: true,
  },
  {
    id: "user-1",
    nombreUsuario: "MagoMatematico",
    experienciaTotal: 380,
    nivel: 12,
    rachaActual: 30,
    ejerciciosCompletados: 22,
    posicion: 2,
  },
  {
    id: "user-5",
    nombreUsuario: "GeometraEstelar",
    experienciaTotal: 320,
    nivel: 6,
    rachaActual: 10,
    ejerciciosCompletados: 18,
    posicion: 3,
  },
]

export const rankingMensual: JugadorRanking[] = [
  {
    id: "user-1",
    nombreUsuario: "MagoMatematico",
    experienciaTotal: 1200,
    nivel: 12,
    rachaActual: 30,
    ejerciciosCompletados: 75,
    posicion: 1,
  },
  {
    id: "user-2",
    nombreUsuario: "DamaCuadratica",
    experienciaTotal: 980,
    nivel: 10,
    rachaActual: 25,
    ejerciciosCompletados: 60,
    posicion: 2,
  },
  {
    id: "user-3",
    nombreUsuario: "EstudianteGenial",
    experienciaTotal: 850,
    nivel: 7,
    rachaActual: 15,
    ejerciciosCompletados: 50,
    posicion: 3,
    esUsuarioActual: true,
  },
]
