// =============================================================================
// DATOS DE LA TIENDA - Matemáticas en Verso
// =============================================================================

import type { ArticuloTienda, PlanSuscripcion } from "@/tipos/tienda"

export const articulosTienda: ArticuloTienda[] = [
  {
    id: "pistas-5",
    nombre: "5 Pistas Adicionales",
    descripcion: "Obtén ayuda extra cuando estés atascado en un ejercicio",
    tipo: "consumible",
    precioMonedas: 100,
    icono: "💡",
    cantidad: 5,
    colorFondo: "bg-amber-100",
    disponible: true,
  },
  {
    id: "fragmento-poema",
    nombre: "Fragmento de Poema",
    descripcion: "Desbloquea un fragmento aleatorio de un poema épico",
    tipo: "consumible",
    precioMonedas: 500,
    icono: "📜",
    colorFondo: "bg-violet-100",
    disponible: true,
    destacado: true,
  },
  {
    id: "doble-xp",
    nombre: "Doble XP (1 hora)",
    descripcion: "Duplica la experiencia ganada durante una hora",
    tipo: "consumible",
    precioMonedas: 200,
    icono: "⚡",
    colorFondo: "bg-emerald-100",
    disponible: true,
  },
  {
    id: "protector-racha",
    nombre: "Protector de Racha",
    descripcion: "Protege tu racha por un día si no puedes practicar",
    tipo: "consumible",
    precioMonedas: 150,
    icono: "🛡️",
    colorFondo: "bg-blue-100",
    disponible: true,
  },
  {
    id: "tema-oscuro",
    nombre: "Tema Nocturno",
    descripcion: "Desbloquea el tema oscuro para la aplicación",
    tipo: "permanente",
    precioMonedas: 1000,
    icono: "🌙",
    colorFondo: "bg-slate-100",
    disponible: true,
  },
  {
    id: "avatar-especial",
    nombre: "Avatar Especial",
    descripcion: "Un avatar único para tu perfil",
    tipo: "permanente",
    precioMonedas: 800,
    icono: "👤",
    colorFondo: "bg-pink-100",
    disponible: true,
  },
]

export const planesSuscripcion: PlanSuscripcion[] = [
  {
    id: "premium-estudiantes",
    nombre: "Versión Premium",
    descripcion: "Para estudiantes individuales",
    tipo: "estudiantes",
    precioMensual: 99,
    precioAnual: 999,
    moneda: "MXN",
    caracteristicas: [
      "Sin anuncios",
      "Pistas ilimitadas",
      "Acceso a todos los poemas",
      "Estadísticas avanzadas",
      "Soporte prioritario",
    ],
    colorFondo: "from-emerald-500 to-emerald-600",
    colorTexto: "text-white",
    popular: true,
  },
  {
    id: "pro-profesores",
    nombre: "Versión Pro",
    descripcion: "Para profesores",
    tipo: "profesores",
    precioMensual: 299,
    precioAnual: 2999,
    moneda: "MXN",
    caracteristicas: [
      "Todo de Premium",
      "Panel de control para estudiantes",
      "Creación de tareas personalizadas",
      "Reportes de progreso",
      "Hasta 50 estudiantes",
    ],
    colorFondo: "from-amber-500 to-amber-600",
    colorTexto: "text-white",
  },
  {
    id: "enterprise-escuelas",
    nombre: "Versión Enterprise",
    descripcion: "Para escuelas",
    tipo: "escuelas",
    precioMensual: 999,
    precioAnual: 9999,
    moneda: "MXN",
    caracteristicas: [
      "Todo de Pro",
      "Estudiantes ilimitados",
      "Integración con sistemas escolares",
      "Reportes institucionales",
      "Soporte dedicado 24/7",
      "Personalización de marca",
    ],
    colorFondo: "from-violet-500 to-violet-600",
    colorTexto: "text-white",
  },
]
